language: generic
os:
  - osx
osx_image: xcode9.4

addons:
  homebrew:
    packages:
      - awscli
      - openssl
    update: true

env:
  matrix:
    - ELECTRON_VERSION="4.0.5" NODE_VERSION="10.11.0"

install:
  - "./prepare-${TRAVIS_OS_NAME}.sh"

script:
  - "./build-${TRAVIS_OS_NAME}.sh"
